# Generated by Django 3.1 on 2020-08-25 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200824_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='iamge',
            new_name='image',
        ),
    ]
