# Generated by Django 3.1 on 2020-08-30 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200830_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='user_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_friendship_requests', to='accounts.user'),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='user_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_friendships_requests', to='accounts.user'),
        ),
    ]
