# Generated by Django 3.1 on 2020-08-31 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20200830_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='content',
        ),
        migrations.AddField(
            model_name='notification',
            name='verb',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
