# Generated by Django 3.1 on 2020-09-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20200831_2221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='notification',
            name='content',
            field=models.TextField(default='<p>mohamed samir sent you a friend request </p>'),
            preserve_default=False,
        ),
    ]
