# Generated by Django 3.1.1 on 2020-09-02 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200902_1742'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MessageRequest',
        ),
    ]
