# Generated by Django 3.1 on 2020-08-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thread',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
