# Generated by Django 3.1.1 on 2020-09-02 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_delete_messagerequest'),
        ('conversations', '0002_auto_20200825_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PEN', 'Pending'), ('ACT', 'Active')], default='PEN', max_length=3)),
                ('user_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_message_requests', to='accounts.user')),
                ('user_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_message_requests', to='accounts.user')),
            ],
        ),
    ]
