# Generated by Django 3.1.1 on 2020-10-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_messagerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('SEN', 'Seen'), ('DLV', 'Delivered'), ('SNT', 'Sent')], default='SNT', max_length=3),
        ),
    ]
