# Generated by Django 3.1.1 on 2020-10-19 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_bio'),
        ('conversations', '0004_message_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='viewers',
            field=models.ManyToManyField(to='accounts.User'),
        ),
    ]
